### ISSUE TITLE
StopIteration exception in encode_images.py

### ISSUE THREAD

**Issue by armheb** [pbaylies/stylegan-encoder#48]
I'm using the StyleGAN_Encoder_Tutorial notebook in google colab but whe running the: `!python encode_images.py aligned_images/ generated_images/ latent_representations/ \
    --vgg_url=https://rolux.org/media/stylegan/vgg16_zhang_perceptual.pkl \
    --batch_size=2`
cell, I get the following error:
Using TensorFlow backend.
Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Loading... Done.
Setting up TensorFlow plugin "upfirdn_2d.cu": Preprocessing... Loading... Done.
Traceback (most recent call last):
  File "encode_images.py", line 243, in <module>
    main()
  File "encode_images.py", line 118, in main
    generator = Generator(Gs_network, args.batch_size, randomize_noise=args.randomize_noise)
  File "/content/stylegan2/encoder/generator_model.py", line 62, in __init__
    self.dlatent_variable = next(v for v in tf.global_variables() if 'learnable_dlatents' in v.name)
StopIteration

**Comment by 15122901359** [comment]
> I'm using the StyleGAN_Encoder_Tutorial notebook in google colab but whe running the: `!python encode_images.py aligned_images/ generated_images/ latent_representations/ \ --vgg_url=https://rolux.org/media/stylegan/vgg16_zhang_perceptual.pkl \ --batch_size=2`
> cell, I get the following error:
> Using TensorFlow backend.
> Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Loading... Done.
> Setting up TensorFlow plugin "upfirdn_2d.cu": Preprocessing... Loading... Done.
> Traceback (most recent call last):
> File "encode_images.py", line 243, in
> main()
> File "encode_images.py", line 118, in main
> generator = Generator(Gs_network, args.batch_size, randomize_noise=args.randomize_noise)
> File "/content/stylegan2/encoder/generator_model.py", line 62, in **init**
> self.dlatent_variable = next(v for v in tf.global_variables() if 'learnable_dlatents' in v.name)
> StopIteration

Hello, have you solved the problem? I also encountered this problem and would like to ask how did you solve it in the end?
