### ISSUE TITLE
requirements.txt empty and compatibility issues

### ISSUE THREAD

**Issue by nPellejero** [pbaylies/stylegan-encoder#61]
Hi , i am trying to train resnet with my own stylegan model , but I am having different compatibility issues. Also, requirements.txt is empty so I am not sure what version of every dependency should I have.

Currently when train step is done and the script tries to save the model, there is this error:

`New best test loss : 0.01359
Saving model.
Traceback (most recent call last):
  File "train_resnet.py", line 261, in <module>
    finetune_resnet(model, args.model_path, model_res=args.model_res, image_size=args.image_size, batch_size=args.batch_size, test_size=args.test_size, max_patience=args.max_patience, n_epochs=args.epochs, seed=args.seed, minibatch_size=args.minibatch_size, truncation=args.truncation)
  File "train_resnet.py", line 202, in finetune_resnet
    model.save(save_path)
  File "/home/npellejero/instalaciones/anaconda3-2/envs/tf-gpu/lib/python3.7/site-packages/keras/engine/network.py", line 1152, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/npellejero/instalaciones/anaconda3-2/envs/tf-gpu/lib/python3.7/site-packages/keras/engine/saving.py", line 449, in save_wrapper
    save_function(obj, filepath, overwrite, *args, **kwargs)
  File "/home/npellejero/instalaciones/anaconda3-2/envs/tf-gpu/lib/python3.7/site-packages/keras/engine/saving.py", line 541, in save_model
    _serialize_model(model, h5dict, include_optimizer)
  File "/home/npellejero/instalaciones/anaconda3-2/envs/tf-gpu/lib/python3.7/site-packages/keras/engine/saving.py", line 163, in _serialize_model
    if isinstance(model.optimizer, optimizers.TFOptimizer):
AttributeError: module 'tensorflow.keras.optimizers' has no attribute 'TFOptimizer'
`
It seems to be keras or tensorflow version in this case the ones that are not compatible, I think. 

thanks in advance for any hint.

**Comment by pbaylies** [comment]
Hi @nPellejero ,

Sorry, this is a pretty old repo; try Keras 2.3.1 and tensorflow-gpu 1.15.0 or look here: https://github.com/pbaylies/stylegan2-ada/
